port: env(PORT)

settings:
  loggerFormat: tiny
  session:
    store: '@foal/typeorm'

database:
  type: better-sqlite3
  database: './db.sqlite3'

intPorn: 
  loginUri: https://forum.intporn.com/login
  createChatUri: https://forum.intporn.com/conversations/add
  file: ./temp/int_user.txt
  resultFile: ./temp/int_result.json
  user: thangnv
  pwd: thangnv123
  message:
    title: 'Hello a new day with the hot neighbor'
    body: '<p><br><img src="https://img33.imagetwist.com/th/41222/qcsk091abbsk.jpg" class="fr-fic fr-dii"><img src="https://img251.imagetwist.com/th/41222/q4amxmfje6qh.jpg" class="fr-fic fr-dii"><br><span lang="en">Enjoy the video: https://droplink.co/1pttt</span></p>'